# Generated by Django 2.0.4 on 2018-04-11 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vuln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CVE', models.CharField(max_length=30)),
                ('dateStart', models.DecimalField(decimal_places=0, max_digits=30)),
                ('dateEnd', models.DecimalField(decimal_places=0, max_digits=30)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
